### ISSUE TITLE
Can't add https://thinkinbtc.com

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#103]
I tried to add https://thinkinbtc.com but always show error messages because of the URL. Tried to remove the s com https, but didn't work too.

Thanks.

**Comment by bitcoinuser** [comment]
Description: a Lightning powered e-commerce store spreading recognition of the Satoshi
Sector: Tshirt

**Comment by pedro-roberto** [comment]
The response code for the website was 302 so the server thought it was a bad URL. Now these response codes will be valid too. Added.
