### ISSUE TITLE
Can't add my site maybe domain extension issue?

### ISSUE THREAD

**Issue by mmvphil** [lightningnetworkstores/lightningnetworkstores.github.io#120]
We have a website fully LN powered we are launching

https://bitX.press
Keeps saying DOMAIN IN USE or ALREADY THERE??
It won't let us add it.

02c8ca5511b7646546728dda5788a365564a7916832815b72e5aa75ff60e722256@173.208.150.210:9735

Can you advise?

Cheers,

Pete

**Comment by pedro-roberto** [comment]
I think this is an issue with websites with unusual top level domains, not recognized by regdom4j. 

I added it manually, it's there now.

**Comment by mmvphil** [comment]
Cheers.. will fund it

**Comment by mmvphil** [comment]
A bitcoin Lightning Powered Social Platform AND the most FUN BOWLING for bits game!

**Comment by pedro-roberto** [comment]
Changed it.

**Comment by mmvphil** [comment]
------ sorry ----- slight issue.
Not sure how it happened but that node ID was not correct.. the domain part was but not the id.. maybe lnd.conf changed it not sure but we are  .. alias **peppertiger** listed on 1ml
03cebf40a97959ae43c52a2a70e6a0160925d4b0e7bbdb845468250b6fb5b76239@173.208.150.210:9735

**Comment by mmvphil** [comment]
Will boost my UPvotes when that is fixed.. again sorry for cause more DB work :(
