### ISSUE TITLE
Bitlum and Bottle, edits to wallets.json

### ISSUE THREAD

**Issue by sgornick** [lightningnetworkstores/lightningnetworkstores.github.io#132]
Bitlum has shut down.

Bottle will be shutting down in a couple weeks.

There is at least one new one, as well:

Phoenix wallet ( phoenix.acinq.co ) [Announcement](https://medium.com/@ACINQ/introducing-phoenix-5c5cc76c7f9e)

**Comment by pedr0-fr** [comment]
Thank you, will fix it.

**Comment by pedr0-fr** [comment]
Done https://github.com/lightningnetworkstores/lightningnetworkstores.github.io/commit/76671d3c38a4b6cf2786423b7413053f1e938ebd
