### ISSUE TITLE
Add http://www.9bravos.com.br

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#22]
It's a Brazilian book store that accept bitcoin lightning payments:

http://www.9bravos.com.br

Thanks.

**Comment by lightningnetworkstores** [comment]
Thank you, first library I see.

However, I am not able to buy any book through the website... Maybe add it in the coming soon section?

**Comment by bitcoinuser** [comment]
Hi, I tried to buy a book today, and they were having a problem with node. They restarted it and the blockchain is syncronizing. 
So it's already accepting lightning payments.

What problem happened that you were not able to buy?

**Comment by lightningnetworkstores** [comment]
Tried to buy with a book some dummy address/name/email, and when I clicked "proceed to BTCpay" it kept asking me if I had a coupon...

**Comment by bitcoinuser** [comment]
Yes, I talked to them about this, and It's a bug of plugin because blockchain is syncronizing. 
Do not add to lightningnetworkstores yet. Let see later today when their blockhain syncronize to see if us see this bug again.

Thanks. I'll let you know when you can test a payment again.

**Comment by lightningnetworkstores** [comment]
I would also suggest adding some an english translation of the website and some english books as most people that will visit 9bravos from the repository will not speak portuguese (by chance I speak portuguese).

**Comment by rsandrade** [comment]
BTCPay is working with Lightning Network now. :)

**Comment by pedro-roberto** [comment]
Ola Ricardo, thanks for the info. I am busy now, I will add it by Saturday the latest. In the meantime, feel free to make a pull request, it would speed up things. Consider translating the website to english, otherwise 99% of the people that this website redirects to you will just bounce back...

**Comment by lightningnetworkstores** [comment]
Added, feel free to add your nodeid and change description in a pull request.
