### ISSUE TITLE
Add to coming soon: https://wearsmyliberty.com/

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#23]
See: https://twitter.com/WearsMyLiberty/status/990135697745985536?s=19

**Comment by pedro-roberto** [comment]
Thanks one more time... Will be added to the coming soon section. Are you running a twitter bot by any change? :P

**Comment by lightningnetworkstores** [comment]
Thanks one more time.... Will be added to the comming soon section. Are you running a twitter bot by any chance? :P

**Comment by lightningnetworkstores** [comment]
Added to main section
