### ISSUE TITLE
Wallet Addition: coinOS.io 

### ISSUE THREAD

**Issue by RenSylvain** [lightningnetworkstores/lightningnetworkstores.github.io#34]
coinos.io has a web wallet and an android wallet. Please add it to the list when you can :).

**Comment by lightningnetworkstores** [comment]
Just added it in a hurry.... is it for mainnet or testnet?

**Comment by lightningnetworkstores** [comment]
Does it require a previous lightning node to be running?

**Comment by RenSylvain** [comment]
It's for mainnet and it does not require a previous lightning node to be running.

One thing to note about this wallet is that it holds the funds on a centralized database. All accounts are managed on there. That's what makes it so easy and streamlined. All accounts are connected to the creators lightning node. (at least this is my understanding)

regardless, it's a cool wallet.

**Comment by lightningnetworkstores** [comment]
I tried it over the weekend with no success... coinOS node doesn't seem very well connected...

**Comment by asoltys** [comment]
hi coinos author here.. I channeled with yalls now and a couple other nodes if you want to give it another try.

**Comment by pedro-roberto** [comment]
CoinOS was added a while ago... Should have been closed for several weeks.
