### ISSUE TITLE
Hipptee 

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#49]
Move from coming soon to accepting Lightning payments

https://www.reddit.com/r/Bitcoin/comments/8u146j/we_now_accept_lightning_payments_at_hippteecom/

**Comment by Giszmo** [comment]
not an issue. make a PR instead.

(also ... "coming soon" should really not be a thing except maybe for sites that are already functional on testnet.)

**Comment by lightningnetworkstores** [comment]
Added with 928cdd06f6df46a1d1a2df61cfd1b0c8a6aa0024
