### ISSUE TITLE
As user I can rate services anonymously

### ISSUE THREAD

**Issue by Giszmo** [lightningnetworkstores/lightningnetworkstores.github.io#52]
Users should be able to give stars to services. Here you could turn your own service into a lightning-enabled app. Clicking the stars (3.2/5 ★★★☆☆) opens a popup:

    (rate) ★☆☆☆☆ 3000sat
    (rate) ★★☆☆☆ 0sat
    (rate) ★★★☆☆ 0sat
    (rate) ★★★★☆ 0sat
    (rate) ★★★★★ 4000sat

 with details about past ratings. Clicking "rate" should open a payment request without amount, that the site would associate as a rating for the corresponding stars rating. Invoice comment should state "3 star rating for yalls.com" for example.

**Comment by pedro-roberto** [comment]
You more or less guessed what the next update will be :P

**Comment by lightningnetworkstores** [comment]
Closing this as this feature was added. Noted the preference for star ratings instead of upvote/downvote.
