### ISSUE TITLE
Add https://thunderpick.com

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#60]
Add https://thunderpick.com

Obs. It's using coingate.com

![captura de tela de 2018-07-02 18-15-43](https://user-images.githubusercontent.com/1178856/42186733-1bae97e4-7e24-11e8-9272-033f6ab480ff.png)

**Comment by lightningnetworkstores** [comment]
Awesome idea

**Comment by lightningnetworkstores** [comment]
Added to the repository! Backend server will update after 10 minutes or less.
