### ISSUE TITLE
Add https://www.mmoga.com

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#62]
Add https://www.mmoga.com

Obs. They are using coingate.com

![captura de tela de 2018-07-02 19-29-12](https://user-images.githubusercontent.com/1178856/42189387-67c15c52-7e2e-11e8-82e1-0fd889d40183.png)

**Comment by lightningnetworkstores** [comment]
God bless you @bitcoinuser . Are you going to find any more stores or can I go to sleep? :P

**Comment by lightningnetworkstores** [comment]
Added to the repository! :)
