### ISSUE TITLE
Add livejasmin.com

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#82]
Add livejasmin.com

use coingate.com

**Comment by lightningnetworkstores** [comment]
heu @bitcoinuser , where is this list of coingate merchants published?

**Comment by bitcoinuser** [comment]
Hi, the removed the blog post: https://webcache.googleusercontent.com/search?q=cache:YDHDJCApMfwJ:https://blog.coingate.com/2018/07/lightning-network-payments-launched-pilot/+&cd=1&hl=pt-BR&ct=clnk&gl=br

**Comment by lightningnetworkstores** [comment]
I the meanwhile I found it, thanks. Well played. I think livejasmin isn't accepting yet, tried it and didn't see the option.

**Comment by bitcoinuser** [comment]
Good you are testing. I tested only some of the sites.

**Comment by lightningnetworkstores** [comment]
Why do you think coingate removed many of the websites?

**Comment by lightningnetworkstores** [comment]
I mean, removed the blog post.

**Comment by bitcoinuser** [comment]
I don't know but I asked them on Twitter https://twitter.com/twiteis/status/1013879685606969346?s=09

**Comment by pedro-roberto** [comment]
Added.
