### ISSUE TITLE
Add https://www.cannabis-seeds-store.co.uk/

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#86]
Add https://www.cannabis-seeds-store.co.uk/

Use coingate.com

Obs. I tested the checkout page.

**Comment by pedro-roberto** [comment]
hey @bitcoinuser can we speak in private? I am working on an easier way to add stores automatically to the website, would you like to have a password to add them without paying (I am thinking about charging a small amount mostly to prevent spam). Please send me an email to lightningnetworkstores@gmail.com
