### ISSUE TITLE
Add lightning network payment processors

### ISSUE THREAD

**Issue by bitcoinshirt** [lightningnetworkstores/lightningnetworkstores.github.io#87]
I just wrote an article about the payment processors which enable Lightning Network for merchants. 

Here's the [link](https://bitcoinshirt.co/lightning-network-processors-2018/) to the article

TLDR; 
1. BTCPay
2. CoinGate
3. OpenNode
4. GloBee
5. Strike

I thought it would be cool to add this somewhere on the website.

**Comment by pedro-roberto** [comment]
Hi, feel free to make a pull request to about.html with this info

**Comment by bitcoinshirt** [comment]
Hey @pedro-roberto I don't have any experience with submitting changes, just wanted to give a suggestion, if I figure out how to do it, I'll submit it.

**Comment by pedro-roberto** [comment]
Will close this as this will might added via pull request
