### ISSUE TITLE
I was unable to add https://rogueandwolf.com/

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#96]
Hi, https://rogueandwolf.com/ accept lightning payments but I was unable to add it to lightningnetworkstores. The message say that the url already exist. I didn't find it.

Thanks.

**Comment by lightningnetworkstores** [comment]
Can you try with the URL  http://rogueandwolf.com/ and  http://rogueandwolf
.com

Sometimes the "s" in the https or the "/" at the end causes problems
verifying the URL.

**Comment by bitcoinuser** [comment]
Hi,

Tried but show the same error: Seems that store already exists: url in use

**Comment by pedro-roberto** [comment]
Added
